openapi: 3.0.0
x-stoplight:
  id: 79kj9ijbhrxtr
info:
  title: Courses
  version: '1.0'
  contact:
    name: Miroslav Holec
    email: mirek@miroslavholec.cz
  description: API pro správu kurzů
tags:
  - name: Courses
    description: Bla bla
servers:
  - url: 'https://localhost:3000'
    description: Local
  - url: 'https://restdemo.miroslavholec.cz/api'
    description: Production
paths:
  '/courses/{id}':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
    get:
      summary: Get Course
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
              examples:
                Default:
                  value:
                    id: 1
                    title: Výchozí kurz
                    price: 900
                    date: '2019-08-24T14:15:22Z'
                    attendees: 10
                    rating: 10
                Empty:
                  value:
                    id: 2
                    title: Prázdný kurz
                    price: 900
                    date: '2019-08-24T14:15:22Z'
                    attendees: 0
                    rating: 0
        '500':
          $ref: '#/components/responses/ProblemDetails'
      operationId: GetCourseById
      description: Získání kurzu
      tags:
        - Courses
  /courses:
    get:
      summary: Get Courses
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Courses'
              examples: {}
        '500':
          $ref: '#/components/responses/ProblemDetails'
      operationId: GetCourses
      parameters:
        - $ref: '#/components/parameters/take'
        - $ref: '#/components/parameters/skip'
      tags:
        - Courses
      description: Získání seznamu kurzů
    post:
      summary: Create Course
      operationId: CreateCourse
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
        '500':
          $ref: '#/components/responses/ProblemDetails'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseCreate'
        description: ''
      tags:
        - Courses
      description: Vytvoření nového kurzu
    parameters: []
components:
  schemas:
    Course:
      title: Course
      x-stoplight:
        id: xu8ydriz7hd99
      type: object
      x-examples:
        Default:
          id: 1
          title: Název kurzu
          price: 900
          date: '2019-08-24T14:15:22Z'
          attendees: 1
          rating: 5
      description: Detail kurzu
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          x-stoplight:
            id: faiutxmh39t7j
          example: Název kurzu
        price:
          type: number
          x-stoplight:
            id: v3qp1l8ize0af
          format: double
          minimum: 0
          maximum: 80000
          description: uvedena v czk
          example: 900
        date:
          type: string
          x-stoplight:
            id: 86k61d9h2i25x
          format: date-time
        attendees:
          type: integer
          x-stoplight:
            id: x8wczycjdihhf
          format: int32
          minimum: 0
          example: 1
        rating:
          type: integer
          x-stoplight:
            id: 8z673vgfitiou
          minimum: 0
          maximum: 10
          example: 5
    Courses:
      title: Courses
      x-stoplight:
        id: u4hclg9al5nat
      type: object
      properties:
        totalItems:
          type: integer
          x-stoplight:
            id: h7x38iw4lnfmd
          format: int32
        items:
          type: array
          x-stoplight:
            id: 9g2dn9abtzzo0
          items:
            $ref: '#/components/schemas/Course'
    CourseCreate:
      title: CourseCreate
      x-stoplight:
        id: htblt4alqlzof
      type: object
      properties:
        title:
          type: string
          x-stoplight:
            id: fb9ggm19zpmlw
          minLength: 2
          maxLength: 20
        price:
          type: number
          x-stoplight:
            id: n174qq3uq01i7
          format: double
        date:
          type: string
          x-stoplight:
            id: k4nvoidavto1p
          format: date-time
      required:
        - title
        - price
        - date
    ProblemDetails:
      title: ProblemDetails
      x-stoplight:
        id: dvdppmfxltthe
      type: object
      properties:
        type:
          type: string
          x-stoplight:
            id: kzbgxdb0djq1o
        title:
          type: string
          x-stoplight:
            id: 0gi9azyeerhbl
      description: Obecná chybová struktura
  responses:
    ProblemDetails:
      description: Obecná chybová struktura
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
          examples:
            Standard:
              value:
                type: 'https://ddds'
                title: Internal Server Errror
  parameters:
    take:
      name: take
      in: query
      required: false
      schema:
        type: integer
        minimum: 0
        default: 10
        format: int32
      description: Počet položek k načtení
    skip:
      name: skip
      in: query
      required: false
      schema:
        type: integer
        default: 0
        minimum: 0
        format: int32
      description: Počet položek k přeskočení
  examples: {}
